-- CampusMate: Advisors + secured GPA (PostgreSQL migration)
-- Run AFTER project.sql. Safe on empty tables; if Students already has
-- advisor_id values pointing at staff_id, migrate them before step 2.

-- 1) Advisors: a staff member who acts as an academic advisor
CREATE TABLE advisors (
    advisor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INT NOT NULL UNIQUE,
    status VARCHAR(10) NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (staff_id)
        REFERENCES staff(staff_id)
        ON DELETE CASCADE
);


-- 2) Students.advisor_id now points to advisors (was staff)
ALTER TABLE Students DROP CONSTRAINT fk_student_advisor;

ALTER TABLE Students
ADD CONSTRAINT fk_student_advisor
    FOREIGN KEY (advisor_id)
    REFERENCES advisors(advisor_id)
    ON DELETE SET NULL;

CREATE INDEX idx_students_advisor ON Students(advisor_id);


-- 3) GPA lives in its OWN table, never inside Students.
--    Robot / public endpoints and views must never join this table.
CREATE TABLE student_gpa (
    student_id INT PRIMARY KEY,
    cumulative_gpa NUMERIC(3, 2) NOT NULL
        CHECK (cumulative_gpa >= 0 AND cumulative_gpa <= 4),
    credit_hours_earned INT NOT NULL DEFAULT 0
        CHECK (credit_hours_earned >= 0),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (student_id)
        REFERENCES Students(student_id)
        ON DELETE CASCADE
);

CREATE TRIGGER trg_student_gpa_updated_at
BEFORE UPDATE ON student_gpa
FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- 4) Role used by the API to authorize advisors
INSERT INTO Roles (role_name) VALUES ('Advisor')
ON CONFLICT (role_name) DO NOTHING;


-- 5) Advisor's student list (WITHOUT GPA, safe for general listings)
CREATE VIEW advisor_students AS
SELECT
    a.advisor_id,
    a.staff_id AS advisor_staff_id,
    s.student_id,
    s.student_code,
    s.first_name,
    s.last_name,
    s.email,
    s.group_id,
    s.status
FROM advisors a
JOIN Students s
    ON s.advisor_id = a.advisor_id;


-- 6) Keep GPA away from every DB user except the backend admin.
--    (nlp_1 only has SELECT on students_cleaned, so it is already blocked.)
REVOKE ALL ON student_gpa FROM PUBLIC;