-- CampusMate: Buildings / Floors / Rooms + Competitions (PostgreSQL migration)
-- Run AFTER project.sql (and advisor_gpa_migration.sql if you use it).
-- Subjects, groups, professors, TAs, schedules, events and professor status
-- ALREADY exist in project.sql under different names (see mapping in chat).


-- 1) Buildings
CREATE TABLE buildings (
    building_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_name VARCHAR(100) NOT NULL UNIQUE,
    building_code VARCHAR(20) UNIQUE
);


-- 2) Floors (each floor belongs to one building)
CREATE TABLE floors (
    floor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id INT NOT NULL,
    floor_number INT NOT NULL,

    FOREIGN KEY (building_id)
        REFERENCES buildings(building_id)
        ON DELETE CASCADE,

    UNIQUE (building_id, floor_number)
);


-- 3) Rooms (each room belongs to one floor)
CREATE TABLE rooms (
    room_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_id INT NOT NULL,
    room_code VARCHAR(30) NOT NULL,

    room_type VARCHAR(20) NOT NULL DEFAULT 'Lecture Hall'
        CHECK (room_type IN ('Lecture Hall', 'Lab', 'Section Room', 'Office', 'Other')),

    capacity INT CHECK (capacity IS NULL OR capacity > 0),

    status VARCHAR(10) NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Inactive')),

    FOREIGN KEY (floor_id)
        REFERENCES floors(floor_id)
        ON DELETE CASCADE,

    UNIQUE (floor_id, room_code)
);


-- 4) Link existing tables to rooms (old text columns stay until data is migrated)
ALTER TABLE Schedule ADD COLUMN room_id INT;
ALTER TABLE Schedule
    ADD CONSTRAINT fk_schedule_room
    FOREIGN KEY (room_id) REFERENCES rooms(room_id);

ALTER TABLE events ADD COLUMN room_id INT;
ALTER TABLE events
    ADD CONSTRAINT fk_events_room
    FOREIGN KEY (room_id) REFERENCES rooms(room_id);

ALTER TABLE staff ADD COLUMN office_room_id INT;
ALTER TABLE staff
    ADD CONSTRAINT fk_staff_office_room
    FOREIGN KEY (office_room_id) REFERENCES rooms(room_id);

CREATE INDEX idx_schedule_room ON Schedule(room_id);


-- 5) Competitions
CREATE TABLE competitions (
    competition_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(150) NOT NULL,
    description TEXT,
    organizer VARCHAR(150),

    room_id INT,

    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    registration_deadline TIMESTAMP,

    max_team_size INT NOT NULL DEFAULT 1
        CHECK (max_team_size > 0),

    status VARCHAR(10) NOT NULL DEFAULT 'Upcoming'
        CHECK (status IN ('Upcoming', 'Open', 'Closed', 'Finished', 'Cancelled')),

    target_department_id INT,

    target_academic_level VARCHAR(10)
        CHECK (target_academic_level IN ('Freshman', 'Sophomore', 'Junior', 'Senior')),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (room_id)
        REFERENCES rooms(room_id),

    FOREIGN KEY (target_department_id)
        REFERENCES Departments(department_id)
);


-- 6) Competition registrations (student joins a competition, optionally in a team)
CREATE TABLE competition_registrations (
    registration_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    competition_id INT NOT NULL,
    student_id INT NOT NULL,

    team_name VARCHAR(100),

    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (competition_id)
        REFERENCES competitions(competition_id)
        ON DELETE CASCADE,

    FOREIGN KEY (student_id)
        REFERENCES Students(student_id)
        ON DELETE CASCADE,

    UNIQUE (competition_id, student_id)
);